version: "3"
services:
  db:
    image: mongo
    container_name: pinger-db-dev
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-dev:/data/db
